# Site settings
title: The Beehive
email: pdxbeehive@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A cute little place in Cully
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pdxbeehive.com" # the base hostname & protocol for your site
image: "/images/homepage/beehive.jpg"

# Build settings
markdown: kramdown

# To show future events
future: true

collections:
  events:
    output: true
    permalink: /events/:path/
  rooms:
    output: true
    permalink: /rooms/:path/
